### PR TITLE
[#15] Implement backend for logout functionality

### PR DESCRIPTION
**Pull request by chornerman**
#15

## What happened 👀

- [x] Create `LogoutRequest`
- [x] Add logout API call in service
- [x] Add logout service call in repository and add corresponding unit tests
- [x] Create `LogoutUseCase` and corresponding unit tests

## Insight 📝

- Once logging out, we will clear all of the caches (both surveys and tokens cache)

## Proof Of Work 📹

```
flutter: *** Request ***
flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/revoke
flutter: method: POST
flutter: responseType: ResponseType.json
flutter: followRedirects: true
flutter: connectTimeout: 30000
flutter: sendTimeout: 0
flutter: receiveTimeout: 30000
flutter: receiveDataWhenStatusError: true
flutter: extra: {}
flutter: headers:
flutter:  content-type: application/json; charset=utf-8
flutter: data:
flutter: {token: HxfsCEPFRtBxIsuGLHG4R11AXUapQ73a5hibBwljPac, client_id: 4gg3bokkvPnMxWz7HHTdM_wf1RNg9k8iA6sZ2ZrA7EA, client_secret: y_GgV-GEjWd3VTzbZBS6tqEco0E68QuqHQv0QND2vKo}
flutter:
flutter: *** Response ***
flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/revoke
flutter: statusCode: 200
flutter: headers:
flutter:  connection: keep-alive
flutter:  cache-control: max-age=0, private, must-revalidate
flutter:  transfer-encoding: chunked
flutter:  date: Mon, 26 Dec 2022 07:43:53 GMT
flutter:  vary: Accept-Encoding, Origin
flutter:  content-encoding: gzip
flutter:  strict-transport-security: max-age=31536000; includeSubDomains
flutter:  referrer-policy: strict-origin-when-cross-origin
flutter:  report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=xUOFiSySBA6dm%2BAtixlwGZWXezDVwC0KUTbd2Q1OwlgG876dcdExKrN35wFEtaLX0owpBP6urhsB5nos9NC38gKHNuJOnXCnhTObwQ46ksLBqx6wycDgJAsCTEksKH3WAu2pKTuq%2FRKc"}],"group":"cf-nel","max_age":604800}
flutter:  cf-cache-status: DYNAMIC
flutter:  x-permitted-cross-domain-policies: none
flutter:  content-type: application/json; charset=utf-8
flutter:  x-xss-protection: 1; mode=block
flutter:  server: cloudflare
flutter:  x-request-id: 3092d64c-dc19-4ac6-92c9-826300e3037b
flutter:  alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
flutter:  nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
flutter:  x-download-options: noopen
flutter:  cf-ray: 77f830275cca5aca-BKK
flutter:  x-runtime: 0.013030
flutter:  etag: W/"5768fdcc51913951060b5cf9e59e6b77"
flutter:  via: 1.1 vegur
flutter:  x-frame-options: SAMEORIGIN
flutter:  x-content-type-options: nosniff
flutter: Response Text:
flutter: {}
flutter:
```

### CODE REVIEW

**Comment by luongvo** [comment]
@chornerman please update the PR's description & detail to make it ready before marking a PR is ready for review 🙏

**Review by luongvo — APPROVED** [review]
rest lgtm

**Comment by chornerman** [comment]
@luongvo Updated 👍🏼

**Comment by luongvo** [comment]
@chornerman looks better 👍

**Review by markgravity — APPROVED** [review]

**Pull request merged**
