### PR TITLE
[#3] Implement UI for Login screen

### PR DESCRIPTION
**Pull request by chornerman**
#3 

## What happened 👀

Implement UI for the Login screen

## Insight 📝

- [x] Add resource files to use in the Login screen (font, background, header icon) using `flutter_gen`
- [x] Implement UI for the Login screen
- [x] Set up localization using `intl `
- [x] Remove unit test for now
- [x] Increase Flutter version for both project and CI/CD

### CODE REVIEW

**Review by markgravity — APPROVED** [review]

**Comment by chornerman** [comment]
@luongvo Regarding [this](https://github.com/chornerman/Survey/pull/56#discussion_r969131532) comment, could you please guide me more 🙏🏼 I'm not sure how I can archive this. How about creating a style class and extracting all TextStyles there? 🤔 

Anyway, the other comments are all resolved. Thank for your review ❤️

**Review by luongvo — APPROVED** [review]
LGTM

**Comment by luongvo** [comment]
> @luongvo Regarding https://github.com/chornerman/Survey/pull/56#discussion_r969131532 comment, could you please guide me more 🙏🏼 I'm not sure how I can archive this. How about creating a style class and extracting all TextStyles there? 🤔

@chornerman I think you can refer to this documentation:
- https://api.flutter.dev/flutter/painting/TextStyle-class.html
and some of our well-done ICs.

You can improve it in the next PRs.

**Comment by luongvo** [comment]
@chornerman please remember to delete unused branches after merging.

**Comment by chornerman** [comment]
> @chornerman please remember to delete unused branches after merging.

Thank you for the reminder 🙏🏼

**Pull request merged**
