### PR TITLE
[#4] Integrate Login screen

### PR DESCRIPTION
**Pull request by chornerman**
#4 

## What happened 👀

Integrate Login screen

## Insight 📝

- [x] Create a view model for the Login screen
- [x] Call `LoginUseCase` when tapping on the login button with information from the inputs
- [x] Set up navigation
- [x] Fix `LoginResponse` mapping
- [x] Upgrade Flutter SDK (including the one defined in GitHub workflows) to use the latest version of libraries
- [x] Add unit tests for `LoginViewModel`
- [x] Set `Codecov` project and patch code coverage target to 0% to avoid failing the CI

## Proof Of Work 📹

**Success case**

https://user-images.githubusercontent.com/13492460/188580465-e9d1b727-3004-4995-b6b3-83b212373a49.mp4

```
2022-09-06 14:34:45.982 31839-31878/co.nimblehq.survey I/flutter: *** Request ***
2022-09-06 14:34:45.985 31839-31878/co.nimblehq.survey I/flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/token
2022-09-06 14:34:45.985 31839-31878/co.nimblehq.survey I/flutter: method: POST
2022-09-06 14:34:45.985 31839-31878/co.nimblehq.survey I/flutter: responseType: ResponseType.json
2022-09-06 14:34:45.985 31839-31878/co.nimblehq.survey I/flutter: followRedirects: true
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: connectTimeout: 30000
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: sendTimeout: 0
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: receiveTimeout: 30000
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: receiveDataWhenStatusError: true
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: extra: {}
2022-09-06 14:34:45.986 31839-31878/co.nimblehq.survey I/flutter: headers:
2022-09-06 14:34:45.987 31839-31878/co.nimblehq.survey I/flutter:  content-type: application/json; charset=utf-8
2022-09-06 14:34:45.987 31839-31878/co.nimblehq.survey I/flutter: data:
2022-09-06 14:34:45.987 31839-31878/co.nimblehq.survey I/flutter: {grant_type: password, email: kaung@nimblehq.co, password: 12345678, client_id: 4gg3bokkvPnMxWz7HHTdM_wf1RNg9k8iA6sZ2ZrA7EA, client_secret: y_GgV-GEjWd3VTzbZBS6tqEco0E68QuqHQv0QND2vKo}
2022-09-06 14:34:45.987 31839-31878/co.nimblehq.survey I/flutter: 
2022-09-06 14:34:47.838 31839-31878/co.nimblehq.survey I/flutter: *** Response ***
2022-09-06 14:34:47.839 31839-31878/co.nimblehq.survey I/flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/token
2022-09-06 14:34:47.839 31839-31878/co.nimblehq.survey I/flutter: statusCode: 200
2022-09-06 14:34:47.839 31839-31878/co.nimblehq.survey I/flutter: headers:
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  date: Tue, 06 Sep 2022 07:34:47 GMT
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  transfer-encoding: chunked
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  vary: Accept-Encoding, Origin
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  content-encoding: gzip
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  pragma: no-cache
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  server: cloudflare
2022-09-06 14:34:47.841 31839-31878/co.nimblehq.survey I/flutter:  x-request-id: e31f48e6-7a3f-4505-8dbe-551df9f5a73f
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  cf-ray: 7465862ccd7426e3-BKK
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  etag: W/"5ce0fd923873bf499c7704f8bb292c91"
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-frame-options: SAMEORIGIN
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  connection: keep-alive
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  cache-control: private, no-store
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  strict-transport-security: max-age=31536000; includeSubDomains
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  referrer-policy: strict-origin-when-cross-origin
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  cf-cache-status: DYNAMIC
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5D%2BtH2xvTmZK2sELbYLlorZTamZY0GrQyGS%2BMkOuxpioG0UZW2gSuO2IdzwBpb4U5C%2Bi3j%2Bf0TrVehp9wILnelP20Z06fCrG%2BWkVN19pJzmY8KsYnYyxpgQw%2BdT24ipSvTsvcyrOTPBsvIEh8DZSqquwlqbh"}],"group":"cf-nel","max_age":604800}
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-permitted-cross-domain-policies: none
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  content-type: application/json; charset=utf-8
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-xss-protection: 1; mode=block
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-download-options: noopen
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-runtime: 0.515929
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  via: 1.1 vegur
2022-09-06 14:34:47.842 31839-31878/co.nimblehq.survey I/flutter:  x-content-type-options: nosniff
2022-09-06 14:34:47.843 31839-31878/co.nimblehq.survey I/flutter: Response Text:
2022-09-06 14:34:47.843 31839-31878/co.nimblehq.survey I/flutter: {"data":{"id":"10594","type":"token","attributes":{"access_token":"_gPw_bQNR9bllfPNqNT9p77H819vQrCR5KFzs5b5Ayw","token_type":"Bearer","expires_in":7200,"refresh_token":"MKxlEHg8_4wLKC0qUTJWc7Lrtf5I2a5qBkM8lPj4CEs","created_at":1662449687}}}
2022-09-06 14:34:47.843 31839-31878/co.nimblehq.survey I/flutter: 
```

**Error case**

https://user-images.githubusercontent.com/13492460/188580510-4c91dc41-5ecc-48d8-96a2-cc27de998570.mp4

```
2022-09-06 14:48:04.541 31839-31878/co.nimblehq.survey I/flutter: *** Request ***
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/token
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: method: POST
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: responseType: ResponseType.json
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: followRedirects: true
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: connectTimeout: 30000
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: sendTimeout: 0
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: receiveTimeout: 30000
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: receiveDataWhenStatusError: true
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: extra: {}
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: headers:
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter:  content-type: application/json; charset=utf-8
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: data:
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: {grant_type: password, email: error@email.com, password: 12345678, client_id: 4gg3bokkvPnMxWz7HHTdM_wf1RNg9k8iA6sZ2ZrA7EA, client_secret: y_GgV-GEjWd3VTzbZBS6tqEco0E68QuqHQv0QND2vKo}
2022-09-06 14:48:04.542 31839-31878/co.nimblehq.survey I/flutter: 
2022-09-06 14:48:05.563 31839-31878/co.nimblehq.survey I/flutter: *** DioError ***:
2022-09-06 14:48:05.563 31839-31878/co.nimblehq.survey I/flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/token
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter: DioError [DioErrorType.response]: Http status error [400]
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter: uri: https://survey-api.nimblehq.co/api/v1/oauth/token
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter: statusCode: 400
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter: headers:
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  date: Tue, 06 Sep 2022 07:48:05 GMT
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  transfer-encoding: chunked
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  vary: Accept-Encoding, Origin
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  content-encoding: gzip
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  pragma: no-cache
2022-09-06 14:48:05.564 31839-31878/co.nimblehq.survey I/flutter:  www-authenticate: Bearer realm="Doorkeeper", error="invalid_email_or_password", error_description="Your email or password is incorrect. Please try again."
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  server: cloudflare
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-request-id: 2257c797-3962-4576-9b04-5adf2d621635
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  cf-ray: 746599aa7b745be3-BKK
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-frame-options: SAMEORIGIN
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  connection: keep-alive
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  cache-control: private, no-store
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  strict-transport-security: max-age=31536000; includeSubDomains
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  referrer-policy: strict-origin-when-cross-origin
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  cf-cache-status: DYNAMIC
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=cLBnS%2B3ZklzYmVKVhayIPSf4E4CNk9gAWnhHWHIywXCGP8i4IA3LOmUhqy9S0fXbN4%2BMDtKTOs5zLFmKYjXfX1PUKQgCfUtDkxMwpa2kbWaoc%2FY7KI83DF9xSmd8lqrKoxc%2Fh7xkGv0VHqgiEzUhFeGXIO8j"}],"group":"cf-nel","max_age":604800}
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-permitted-cross-domain-policies: none
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  content-type: application/json; charset=utf-8
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-xss-protection: 1; mode=block
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-download-options: noopen
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-runtime: 0.005460
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  via: 1.1 vegur
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter:  x-content-type-options: nosniff
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter: Response Text:
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter: {"errors":[{"detail":"Your email or password is incorrect. Please try again.","code":"invalid_email_or_password"}]}
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter: 
2022-09-06 14:48:05.565 31839-31878/co.nimblehq.survey I/flutter: 
```

**Invalid inputs case**

https://user-images.githubusercontent.com/13492460/188811025-7bc1d4bb-b089-4d74-a4ed-13dc9c32b501.mp4

### CODE REVIEW

**Comment by markgravity** [comment]
Please ignore `*.g.dart`, there are a lot of changes (1000+) in this PR 🙏

**Comment by luongvo** [comment]
> Please ignore `*.g.dart`, there are a lot of changes (1000+) in this PR 🙏

@chornerman according to my review here https://github.com/chornerman/Survey/pull/60#discussion_r982191463, we should consider working on a chore before this PR 🙏

**Review by luongvo — COMMENTED** [review]
rest lgtm @chornerman

**Review by luongvo — APPROVED** [review]
lgtm

**Comment by luongvo** [comment]
@markgravity please review this PR for @chornerman to merge this PR soon 👋

**Review by markgravity — APPROVED** [review]
LGTM now

**Pull request merged**
